trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'da3968b5-e827-4f3b-bb75-231e730aaf97'

  # Virtual machine name
  vmName: 'raj-deploy-VM'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      name: my-agent  # Specify your self-hosted agent pool name here
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'MyWebApp/pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/MyWebApp/target/'
        Contents: '*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToVM
    displayName: Deploy to Virtual Machine
    environment: $(vmName)
    pool:
      name: my-agent  # Specify your self-hosted agent pool name here
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Artifact'
            inputs:
              artifactName: 'drop'
              path: '$(Pipeline.Workspace)/drop'

          - task: CopyFiles@2
            displayName: 'Copy Files to VM'
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/drop/**/*.?(war|jar)'
              TargetFolder: '/home/raj/azagent/'

          # Add additional steps here to execute deployment commands on the VM.
