trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: UpdateSystem
  jobs:
  - job: UpdateSystemJob
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'vm1'
        runOptions: 'commands'
        commands: 'sudo apt update -y'
        readyTimeout: '20000'

- stage: BuildAndTest
  jobs:
  - job: BuildAndTestJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: '/MyWenApp/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

