trigger:
- main  # Trigger the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest version of Ubuntu as the agent VM

variables:
  vmName: 'raj-deploy-VM'        # Azure VM name
  appName: 'sample-java'         # Name of the Java application

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - checkout: self       # Checkout the source code from the repository

    - script: |
        cd $(Build.SourcesDirectory)  # Navigate to the source directory
        mvn clean package  # Build the Java application
      displayName: 'Maven Build'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/target/sample-java.jar'
        artifactName: 'sample-java'
        publishLocation: 'Container'
      displayName: 'Publish JAR as Build Artifact'

    - script: |
        scp $(Build.SourcesDirectory)/target/sample-java.jar $(vmName):~/sample-java.jar
      displayName: 'Copy JAR to VM'

    - script: |
        ssh $(vmName) 'java -jar ~/sample-java.jar'
      displayName: 'Deploy Java Application to VM'
