trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: UpdateSystem
  jobs:
  - job: UpdateSystemJob
    steps:
    - script: |
        sudo apt update -y
      displayName: 'Update system packages'
      continueOnError: true

- stage: BuildAndTest
  jobs:
  - job: BuildAndTestJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'MyWebApp/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
